[package]
name = "charm"
version = "0.1.0"
edition = "2021"

[dependencies]
madsim = "0.2"
tracing = "0.1.40"
tokio = { version = "0.2", package = "madsim-tokio", features = ["full"] }
rand = { version = "0.8.5", features = [] }
derive_builder = "0.20.0"
futures = "0.3.30"
tracing-subscriber = "0.3.18"
clap = { version = "4.5.16", features = ["derive"] }
humantime = "2.1.0"
tonic = "0.12.1"
prost = "0.13.1"
async-stream = "0.3.5"

[build-dependencies]
tonic-build = "0.12.1"
